### ISSUE TITLE
fixes

### ISSUE THREAD

**Issue by ErfXploded** [Roni-sl/R-Leveling-System#2]
Simple leveling system that can be used not only in darkrp

Features
Compatible with any gamemode
Compatible with addons that work with Vrondakis leveling system
Compatible with Job System | Job Employer NPCs
Has darkrp integration
Easy module system
Easily configurable
Compatible with MySQL(MySQLoo, tmysql4) or just sqlite
For devs
That hooks is available:

Serverside:
	RLS.OnLevelChange(Player ply, number level): nothing to return
	RLS.OnExpChange(Player ply, number exp, bool is_level_updated): nothing to return
	RLS.UpdateExpAmount(Player ply, number exp): return number exp
Suggest your modules please
If you have ideas for a module or compatibility with an addon, just open Issue

ToDo
TTT support
Murder support

**Comment by Roni-sl** [comment]
ty, improved :D
